# Generated by Django 4.2.2 on 2023-07-10 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recycle_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='points',
            field=models.IntegerField(default='0'),
        ),
        migrations.CreateModel(
            name='Appoinments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_date', models.DateField(max_length=255)),
                ('pick_up_time', models.TimeField(max_length=255)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('Status', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='recycle_app.users')),
            ],
        ),
    ]
