# Generated by Django 4.2.2 on 2023-07-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle_app', '0002_rename_username_users_phone_number_users_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_name', models.CharField(max_length=255)),
                ('bin_type', models.CharField(max_length=255)),
                ('bin_capacity', models.CharField(max_length=255)),
                ('Status', models.CharField(max_length=255)),
            ],
        ),
    ]
