# Generated by Django 4.2.2 on 2023-08-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle_app', '0005_available_slots_vouchers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available_slots',
            name='Availabilty',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='Usability',
            field=models.BooleanField(default=0),
        ),
    ]
