# Generated by Django 4.2.2 on 2023-08-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle_app', '0006_alter_available_slots_availabilty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bins',
            name='associated',
            field=models.BooleanField(default=0),
        ),
    ]
