# Generated by Django 4.2.2 on 2023-08-15 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recycle_app', '0007_bins_associated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Available_Vouchers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=255)),
                ('Discount', models.IntegerField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reedemed_Vouchers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=255)),
                ('Discount', models.IntegerField(max_length=255)),
                ('Code', models.CharField(max_length=255)),
                ('Usability', models.BooleanField(default=0)),
                ('exp_date', models.DateField(max_length=255)),
                ('user_id', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='recycle_app.users')),
            ],
        ),
        migrations.DeleteModel(
            name='Vouchers',
        ),
    ]
