# Generated by Django 4.2.2 on 2023-08-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle_app', '0009_alter_available_vouchers_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='available_vouchers',
            name='Cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
