# Generated by Django 4.2.2 on 2023-08-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle_app', '0010_available_vouchers_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinments',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appoinments',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
