# Generated by Django 4.2.2 on 2023-09-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle_app', '0011_appoinments_type_appoinments_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinments',
            name='pick_up_address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
